# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2e4c7ed44dda8fa85db17b847ad68d78359e6a2032e03bc367ca3a32624764c72d488490493bef75d6d6f72f687c965f0f3d7b11612d10c888c20f57fbd1336

test:
  secret_key_base: d05587908100cb337b284679d2130259ff63fb944c024c2904ddabe5eabdb1d47ea85ed2084ca61d060b3a0b7124a3ec69d4c2505d829e6c409e5fe758fad4ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
